# Generated by Django 3.0.3 on 2020-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200407_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(default='sin direccion', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.IntegerField(default='099000000'),
        ),
    ]
