# Generated by Django 3.0.3 on 2020-03-13 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='name_product',
            field=models.CharField(default='Random Product', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='quantity_product',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
