# Generated by Django 3.0.3 on 2020-03-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200313_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='quantity_product',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name_product',
            new_name='producto',
        ),
    ]
