# Generated by Django 3.0.3 on 2020-03-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200315_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('donación', 'Donación'), ('solicitud', 'Solicitud de donación')], default='solicitud', max_length=22),
        ),
    ]
